#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : haproxy
Version  : 1.8.13
Release  : 11
URL      : http://www.haproxy.org/download/1.8/src/haproxy-1.8.13.tar.gz
Source0  : http://www.haproxy.org/download/1.8/src/haproxy-1.8.13.tar.gz
Summary  : HA-Proxy is a TCP/HTTP reverse proxy for high availability environments
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: haproxy-bin
Requires: haproxy-config
Requires: haproxy-license
Requires: haproxy-man
BuildRequires : openssl-dev
BuildRequires : pcre-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : zlib-dev

%description
HA-Proxy is a TCP/HTTP reverse proxy which is particularly suited for high
availability environments. Indeed, it can:
- route HTTP requests depending on statically assigned cookies
- spread the load among several servers while assuring server persistence
  through the use of HTTP cookies
- switch to backup servers in the event a main one fails
- accept connections to special ports dedicated to service monitoring
- stop accepting connections without breaking existing ones
- add/modify/delete HTTP headers both ways
- block requests matching a particular pattern

It needs very little resource. Its event-driven architecture allows it to easily
handle thousands of simultaneous connections on hundreds of instances without
risking the system's stability.

%package bin
Summary: bin components for the haproxy package.
Group: Binaries
Requires: haproxy-config
Requires: haproxy-license
Requires: haproxy-man

%description bin
bin components for the haproxy package.


%package config
Summary: config components for the haproxy package.
Group: Default

%description config
config components for the haproxy package.


%package doc
Summary: doc components for the haproxy package.
Group: Documentation
Requires: haproxy-man

%description doc
doc components for the haproxy package.


%package license
Summary: license components for the haproxy package.
Group: Default

%description license
license components for the haproxy package.


%package man
Summary: man components for the haproxy package.
Group: Default

%description man
man components for the haproxy package.


%prep
%setup -q -n haproxy-1.8.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535031883
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
make  %{?_smp_mflags} TARGET=linux2628 USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1

%install
export SOURCE_DATE_EPOCH=1535031883
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/haproxy
cp LICENSE %{buildroot}/usr/share/doc/haproxy/LICENSE
cp doc/gpl.txt %{buildroot}/usr/share/doc/haproxy/doc_gpl.txt
cp ebtree/LICENSE %{buildroot}/usr/share/doc/haproxy/ebtree_LICENSE
%make_install PREFIX=/usr SBINDIR=/usr/bin DOCDIR=/usr/share/doc/haproxy
## install_append content
for contrib in halog iprange systemd; do
make V=1 %{?_smp_mflags} -C contrib/$contrib SBINDIR=/usr/bin
done
for contrib in halog iprange; do
cp contrib/$contrib/$contrib %{buildroot}/usr/bin
done
install -d %{buildroot}/usr/lib/systemd/system
cp contrib/systemd/haproxy.service %{buildroot}/usr/lib/systemd/system
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/halog
/usr/bin/haproxy
/usr/bin/iprange

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/haproxy.service

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/haproxy/*

%files license
%defattr(-,root,root,-)
/usr/share/doc/haproxy/LICENSE
/usr/share/doc/haproxy/ebtree_LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/haproxy.1
